### ISSUE TITLE
9900k-asus-390P花屏

### ISSUE THREAD

**Issue by SaintLoong** [igarashikenshin/Hackintosh-Asus-Prime-Z390P_i9-9900K_RX580#1]
黑果小兵的10.15.3镜像替换成您的EFI，安装启动到苹果进度条的位置就花屏，是我的硬件配置问题还是我的用法不对？请教从哪里排查比较正确呢？
硬件：
cpu: I9 9900k
内存: 海盗船DDR4 3200 16GB x 4
主板 华硕 Prime Z390P
硬盘： 闪迪超极速至尊SATA 500GB + 三星970EVO (os安装盘）+ 4T机械硬盘
显卡： 蓝宝石RX590

请教了，谢谢！

**Comment by igarashikenshin** [comment]
bios设置是怎样的，启动参数加上-v 看看会停在哪个地方呢？

发自我的iPhone

在 2020年2月24日，23:25，saintloong <notifications@github.com> 写道：

﻿

黑果小兵的10.15.3镜像替换成您的EFI，安装启动到苹果进度条的位置就花屏，是我的硬件配置问题还是我的用法不对？请教从哪里排查比较正确呢？
硬件：
cpu: I9 9900k
内存: 海盗船DDR4 3200 16GB x 4
主板 华硕 Prime Z390P
硬盘： 闪迪超极速至尊SATA 500GB + 三星970EVO (os安装盘）+ 4T机械硬盘
显卡： 蓝宝石RX590

请教了，谢谢！

**Comment by SaintLoong** [comment]
小兵大神的镜像安装完再替换您的efi可以进系统，声卡全部驱动了谢谢
