### ISSUE TITLE
前置USB2.0失效，显示器自带喇叭驱动不上

### ISSUE THREAD

**Issue by SaintLoong** [igarashikenshin/Hackintosh-Asus-Prime-Z390P_i9-9900K_RX580#2]
完整的换上您的EFI发现了如下几个情况：
1、9900k自带hdmi输出声卡驱动上了，但RX590的hdmi输出声音没有了
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/1243233/75618236-5fe89c00-5ba6-11ea-87b2-54ad2ab740b7.png">
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/1243233/75618238-69720400-5ba6-11ea-85e4-5a621721309e.png">

2、USB全部变成internal，机箱上前置USB接口2.0插入没有反应，3.0口插入3.0设备显示480Mbps，
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/1243233/75618263-9f16ed00-5ba6-11ea-9d4e-5da7d9e3e699.png">

3、休眠 睡不着，点击休眠菜单等待一会儿，屏幕息屏，风扇停了之后马上屏幕重新被点亮，进入登陆界面
4、Tips 全部照做了
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/1243233/75618351-d8039180-5ba7-11ea-83f3-56ae4e09cbca.png">

我的配置：
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/1243233/75618290-0e8cdc80-5ba7-11ea-8413-a0959f1cf72f.png">
这里显示的没有问题，就是这些，
主板: ASUS PRIME Z390-P
BIOS版本：2606
CPU: Intel® Core™ i9-9900K Processor
内存： 海盗船3200 16GB x 4
核显: Intel® UHD Graphics 630
独显: 蓝宝石 Radeon RX 590 8GB GDDR5
板载网卡: Realtek® RTL8111H Gigabit LAN Controller
声卡: Realtek® ALC 887 8-Channel High Definition Audio
固态硬盘: Samsung SSD 970 EVO 500GB 
                闪迪超极速至尊 SSD 500GB
                HGST（日立） 4000GB 机械硬盘
图片不能上传成功，能否添加个联系方式指导下，我的qq：11669391，请喝杯咖啡还是必须的，哈哈！

**Comment by igarashikenshin** [comment]
你先尝试我新更新的1.2，我加入了usbport.kext和usbpower.kext

**Comment by SaintLoong** [comment]
声卡，休眠全可以了，谢谢！
