### ISSUE TITLE
前置面板3.5mm接口无反应

### ISSUE THREAD

**Issue by Sway-Chan** [igarashikenshin/Hackintosh-Asus-Prime-Z390P_i9-9900K_RX580#3]
跟您用的同一个板，CPU i7-9700K。
目前用的是您最新的oc 文件，由于暂时还未购买显卡，改了config里面的显卡ID，让其支持独显启动。
目前用起来基本都正常，但是有碰到三个问题：
1、前置的3.5mm无反应，声音跟麦克风皆是如此，后置接口可以正常输出跟输入
2、USB无法唤醒睡眠，只能通过按开机键。
3、睡眠唤醒之后，登陆界面亮起之后会自动重启。

不知道您是否知道如何解决，以及我是否需要对其做一些额外的修改？不胜感激。

**Comment by igarashikenshin** [comment]
1、前置3.5mm无反应可以在windows下面排下障吗？我这边是完全正常的。
2、EFI/OC/ACPI/SSDT-GPRW.aml 这个文件是定制power键唤醒睡眠的，如果需要usb唤醒睡眠，可以去掉这个文件并在config的acpi-patch中去掉GPRW TO XPRW。
3、睡眠唤醒之后，登陆界面亮起之后会自动重启。 你可以翻一下power log和kernel log吗？在这个issues回复我就可以。

**Comment by Sway-Chan** [comment]
忘记告知了，我机型设置是iMac 19,2
1、前置3.5mm在Windows下设置为97面板，可以正常使用。
3、电源日志在异常事件左右只有一条记录：reventDisplaySleep "com.apple.powermanagement.delayDisplayOff" 00:00:00  id:0x0x1000008002 [System: PrevIdle PrevDisp DeclUser IntPrevDisp kDisp]  
内核崩溃日志：有点长，传不了附件，前面一串编码的我就不复制了。
{
	"timestamp": "2020-03-30 01:26:52.20 +0800",
	"bug_type": "210",
	"os_version": "Mac OS X 10.15.4 (19E266)"
}
"notes": "Stackshot source : disk",
"macOSPanicString": "panic(cpu 0 caller 0xffffff801ac16487): \"AppleHDAHDMI_DPDriver::setPowerState(0xffffff804cf83800 : 0xffffff7f9cc406f8, 0 -> 1) timed out after 10224 ms\"@\/AppleInternal\/BuildRoot\/Library\/Caches\/com.apple.xbs\/Sources\/xnu\/xnu-6153.101.6\/iokit\/Kernel\/IOServicePM.cpp:5296\nBacktrace (CPU 0), Frame : Return Address\n0xffffff821a0fbb40 : 0xffffff801a5215cd \n0xffffff821a0fbb90 : 0xffffff801a65a3c5 \n0xffffff821a0fbbd0 : 0xffffff801a64bf7e \n0xffffff821a0fbc20 : 0xffffff801a4c7a40 \n0xffffff821a0fbc40 : 0xffffff801a520c97 \n0xffffff821a0fbd40 : 0xffffff801a521087 \n0xffffff821a0fbd90 : 0xffffff801acc2c7c \n0xffffff821a0fbe00 : 0xffffff801ac16487 \n0xffffff821a0fbe50 : 0xffffff801ac15d69 \n0xffffff821a0fbe60 : 0xffffff801ac2d2fe \n0xffffff821a0fbea0 : 0xffffff801ac14b18 \n0xffffff821a0fbec0 : 0xffffff801a563545 \n0xffffff821a0fbf40 : 0xffffff801a563071 \n0xffffff821a0fbfa0 : 0xffffff801a4c713e \n\nBSD process name corresponding to current thread: kernel_task\nBoot args: agdpmod=pikera\n\nMac OS version:\n19E266\n\nKernel version:\nDarwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15\/RELEASE_X86_64\nKernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6\nKernel slide:     0x000000001a200000\nKernel text base: 0xffffff801a400000\n__HIB  text base: 0xffffff801a300000\nSystem model name: iMac19,2 (Mac-63001698E7A34814)\nSystem shutdown begun: NO\nPanic diags file available: YES (0x0)\n\nSystem uptime in nanoseconds: 17306905066833\nlast loaded kext at 11175172069385: >!AXsanScheme\t3 (addr 0xffffff7f9e243000, size 32768)\nlast unloaded kext at 11316422950065: >!AXsanScheme\t3 (addr 0xffffff7f9e243000, size 32768)\nloaded kexts:\ncom.google.drivefs.filesystems.dfsfuse\t37.0.8\ncom.insanelymac.RealtekRTL8111\t2.2.2\nru.joedm.SMCSuperIO\t1.1.1\nas.vit9696.SMCProcessor\t1.1.1\nas.vit9696.VirtualSMC\t1.1.1\nas.vit9696.!AALC\t1.4.7\nas.vit9696.WhateverGreen\t1.3.7\nas.vit9696.Lilu\t1.4.2\n>AudioAUUC\t1.70\n@fileutil\t20.036.15\n@filesystems.autofs\t3.0\n@filesystems.ntfs\t3.14.3\n>AGPM\t111.4.4\n>!APlatformEnabler\t2.7.0d0\n>X86PlatformShim\t1.0.0\n>!AUpstreamUserClient\t3.6.8\n>!AMCCSControl\t1.11\n>!AHDA\t283.15\n>!AGraphicsDevicePolicy\t5.1.16\n@AGDCPluginDisplayMetrics\t5.1.16\n>!AHV\t1\n|IOUserEthernet\t1.0.1\n|IO!BSerialManager\t7.0.4f6\n>pmtelemetry\t1\n>!A!IKBLGraphics\t14.0.5\n@Dont_Steal_Mac_OS_X\t7.0.0\n@private.KextAudit\t1.0\n>!A!IPCHPMC\t2.0.1\n>!A!ICFLGraphicsFramebuffer\t14.0.5\n>!A!ISlowAdaptiveClocking\t4.0.0\n>!A16X50ACPI\t3.2\n>!AVirtIO\t1.0\n@filesystems.hfs.kext\t522.100.5\n@!AFSCompression.!AFSCompressionTypeDataless\t1.0.0d1\n@BootCache\t40\n@!AFSCompression.!AFSCompressionTypeZlib\t1.0.0\n@filesystems.apfs\t1412.101.1\n>AirPort.BrcmNIC\t1400.1.1\n>!AAHCIPort\t341.0.2\n>!ARTC\t2.0\n>!AACPIButtons\t6.1\n>!AHPET\t1.8\n>!ASMBIOS\t2.1\n>!AAPIC\t1.7\n$!AImage4\t1\n@nke.applicationfirewall\t303\n$TMSafetyNet\t8\n@!ASystemPolicy\t2.0.0\n|EndpointSecurity\t1\n@kext.triggers\t1.0\n>!ASMBus!C\t1.0.18d1\n|IOSMBus!F\t1.1\n>DspFuncLib\t283.15\n@kext.OSvKernDSPLib\t529\n>!AGraphicsControl\t5.1.16\n|IOAVB!F\t840.3\n>!ASSE\t1.0\n>X86PlatformPlugin\t1.0.0\n@!AGPUWrangler\t5.1.16\n>!AHDA!C\t283.15\n|IOHDA!F\t283.15\n|IONDRVSupport\t575.1\n>IOPlatformPlugin!F\t6.0.0d8\n@!AGraphicsDeviceControl\t5.1.16\n|IOAccelerator!F2\t438.4.5\n|IOGraphics!F\t575.1\n|IOSlowAdaptiveClocking!F\t1.0.0\n>!A16X50Serial\t3.2\n@plugin.IOgPTPPlugin\t840.3\n|IOEthernetAVB!C\t1.1.0\n|Broadcom!BHost!CUSBTransport\t7.0.4f6\n|IO!BHost!CUSBTransport\t7.0.4f6\n|IO!BHost!CTransport\t7.0.4f6\n|IO!B!F\t7.0.4f6\n|IO!BPacketLogger\t7.0.4f6\n>usb.networking\t5.0.0\n>usb.!UHostCompositeDevice\t1.2\n>usb.!UHub\t1.2\n|IOAudio!F\t300.2\n@vecLib.kext\t1.2.0\n|IOSerial!F\t11\n|IOSurface\t269.11\n@filesystems.hfs.encodings.kext\t1\n>usb.!UHostPacketFilter\t1.0\n|IOUSB!F\t900.4.2\n|IO80211!F\t1200.12.2b1\n>mDNSOffloadUserClient\t1.0.1b8\n>corecapture\t1.0.4\n|IOSkywalk!F\t1\n|IONVMe!F\t2.1.0\n>!AEFINVRAM\t2.1\n|IOAHCI!F\t290.0.1\n>usb.!UXHCIPCI\t1.2\n>usb.!UXHCI\t1.2\n>!AEFIRuntime\t2.1\n|IOHID!F\t2.0.0\n$quarantine\t4\n$sandbox\t300.0\n@kext.!AMatch\t1.0.0d1\n>DiskImages\t493.0.0\n>!AFDEKeyStore\t28.30\n>!AEffaceable!S\t1.0\n>!AKeyStore\t2\n>!UTDM\t489.101.1\n|IOSCSIBlockCommandsDevice\t422.101.1\n>!ACredentialManager\t1.0\n>KernelRelayHost\t1\n>!ASEPManager\t1.0.1\n>IOSlaveProcessor\t1\n|IOUSBMass!SDriver\t157.101.3\n|IOSCSIArchitectureModel!F\t422.101.1\n|IO!S!F\t2.1\n|IOUSBHost!F\t1.2\n>!UHostMergeProperties\t1.2\n>usb.!UCommon\t1.0\n>!ABusPower!C\t1.0\n|CoreAnalytics!F\t1\n>!AMobileFileIntegrity\t1.0.5\n@kext.CoreTrust\t1\n|IOTimeSync!F\t840.3\n|IONetworking!F\t3.4\n|IOReport!F\t47\n>!AACPIPlatform\t6.1\n>!ASMC\t3.1.9\n>watchdog\t1\n|IOPCI!F\t2.9\n|IOACPI!F\t1.4\n@kec.pthread\t1\n@kec.corecrypto\t1.0\n@kec.Libm\t1\n\n\n"

**Comment by Sway-Chan** [comment]
从日志上看，应该是AppleALC驱动引起的，我尝试删除了之后，唤醒不会重启。顺带再请教您一下，主板上需要修改什么设置开机才不会有那个 F1 报错呢，每次异常重启都会跳到那个报错，然后按了F1之后会进入BIOS，退出之后才能正常启动。我尝试把超频改成了手动也不行。

**Comment by igarashikenshin** [comment]
bios设置我白天更新一下到介绍里，另外你的efi打一份包可以发到我的邮箱igarashikenshin@icloud.com


发自我的iPhone

在 2020年3月30日，01:48，Sway Chan <notifications@github.com> 写道：

﻿

从日志上看，应该是AppleALC驱动引起的，我尝试删除了之后，唤醒不会重启。顺带再请教您一下，主板上需要修改什么设置开机才不会有那个 F1 报错呢，每次异常重启都会跳到那个报错，然后按了F1之后会进入BIOS，退出之后才能正常启动。我尝试把超频改成了手动也不行。

**Comment by igarashikenshin** [comment]
AppleHDAHDMI_DPDriver::setPowerState(0xffffff804cf83800 : 0xffffff7f9cc406f8, 0 -> 1) timed out after 10224 ms"
这一条说的很清楚，是唤醒时AppleHDA调用HDMI_DPDriver引起的重启，即可确定一个问题，你的集显在驱动方式上有问题，我看你的efi文件中AAPL,ig-platform-id是根据imac19.2做了变动的，现在weg对9代intel核显已经实现免注入驱动了，这一行是可以取消的，我在imac19.1下测试是没有问题的，你也可以试试我默认的0300983E，9900K和9700K除了超线程外，在显卡方面是基本相同的。

关于前置3.5mm输入输出，这跟你的注入id有关，可以看到PciRoot(0x0)/Pci(0x1f,0x3)，我的注入id是01000000 ，默认的alc887使用该id并不会有问题，所以该问题可能与你的核显驱动有关，当你尝试将核显正常驱动后，我相信这个问题会随之解决。

另外，我在nvram-add-7C436110-AB2A-4BBB-A880-FE41995C9F82-boot-args中有关于amd显卡的参数agdpmod=pikera，当你只使用核显时，你可取消这行参数。

**Comment by Sway-Chan** [comment]
了解，谢谢。一开始我尝试使用的是您文件里默认的0300983E，开机进度条走到一半之后会直接重启，之后修改了该ID才正常启动。我会尝试把核显驱动去除试试，看看情况如何。感谢您的解答。

**Comment by Sway-Chan** [comment]
删除AAPL,ig-platform-id字段同样前置面板无声音，同事睡眠唤醒会重启。
之后同时删除agdpmod字段，无任何改善。
然后尝试机型改为19,1，然后使用您推荐的AAPL,ig-platform-id数值，但是开机过程会直接重启，无法进入系统，删除后正常进入。内核日志报错为：
"macOSPanicString": "panic(cpu 0 caller 0xffffff800fa4c32a): Kernel trap at 0xffffff7f92ff30f0, type 14=page fault, registers:\nCR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x0000000025928000, CR4: 0x00000000003626e0\nRAX: 0x0000000000000000, RBX: 0xffffff80445ed980, RCX: 0x0000000080010000, RDX: 0x0000000000000001\nRSP: 0xffffff81df44ee70, RBP: 0xffffff81df44eeb0, RSI: 0xffffff80415d3010, RDI: 0x0000000000000000\nR8:  0x0000000000000003, R9:  0x0000000000000000, R10: 0x0000000000000000, R11: 0x0000000000000000\nR12: 0x0000000000000001, R13: 0x20c49ba5e353f7cf, R14: 0xffffff8042e94000, R15: 0x0000000000000000\nRFL: 0x0000000000010002, RIP: 0xffffff7f92ff30f0, CS:  0x0000000000000008, SS:  0x0000000000000010\nFault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 2, VF: 5\n\nBacktrace (CPU 0), Frame : Return Address\n0xffffff81df44e8d0 : 0xffffff800f9215cd \n0xffffff81df44e920 : 0xffffff800fa5a3c5 \n0xffffff81df44e960 : 0xffffff800fa4bf7e \n0xffffff81df44e9b0 : 0xffffff800f8c7a40 \n0xffffff81df44e9d0 : 0xffffff800f920c97 \n0xffffff81df44ead0 : 0xffffff800f921087 \n0xffffff81df44eb20 : 0xffffff80100c2c7c \n0xffffff81df44eb90 : 0xffffff800fa4c32a \n0xffffff81df44ed10 : 0xffffff800fa4c028 \n0xffffff81df44ed60 : 0xffffff800f8c7a40 \n0xffffff81df44ed80 : 0xffffff7f92ff30f0 \n0xffffff81df44eeb0 : 0xffffff7f92fd096f \n0xffffff81df44eed0 : 0xffffff80100323a6 \n0xffffff81df44ef00 : 0xffffff7f90351052 \n0xffffff81df44ef50 : 0xffffff7f9227a88c \n0xffffff81df44ef60 : 0xffffff7f92283547 \n0xffffff81df44ef80 : 0xffffff800fa4b7cd \n0xffffff81df44efd0 : 0xffffff800f8c7bed \n0xffffff820e233f40 : 0xffffff800f9466c7 \n0xffffff820e233f80 : 0xffffff800f946888 \n0xffffff820e233fa0 : 0xffffff800f8c713e \n      Kernel Extensions in backtrace:\n         com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f90331000->0xffffff7f90369fff\n         com.apple.driver.AppleACPIPlatform(6.1)[06B0C2E0-18E0-3E3B-8A46-17BF2A713C34]@0xffffff7f92273000->0xffffff7f9230dfff\n            dependency: com.apple.iokit.IOACPIFamily(1.4)[9D1FF279-C4A2-3344-902F-E0B22B508689]@0xffffff7f90a45000\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f90331000\n            dependency: com.apple.driver.AppleSMC(3.1.9)[601E041E-0A5C-3B6A-A4E6-45ECC7F48A2B]@0xffffff7f90a57000\n         com.apple.driver.AppleIntelCFLGraphicsFramebuffer(14.0.5)[3A72441D-C2C5-3828-A5AB-B0EE077B7918]@0xffffff7f92f9d000->0xffffff7f931cffff\n            dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f90331000\n            dependency: com.apple.iokit.IOACPIFamily(1.4)[9D1FF279-C4A2-3344-902F-E0B22B508689]@0xffffff7f90a45000\n            dependency: com.apple.iokit.IOAcceleratorFamily2(438.4.5)[33DA860E-90A6-3224-A944-93FA125B054E]@0xffffff7f926ac000\n            dependency: com.apple.iokit.IOReportFamily(47)[337B24B2-0261-3521-8D1B-23387FC1D657]@0xffffff7f906cc000\n            dependency: com.apple.AppleGraphicsDeviceControl(5.1.16)[56FDE242-D4A6-3E8F-A81C-CE9BA61E3828]@0xffffff7f91020000\n            dependency: com.apple.iokit.IOGraphicsFamily(575.1)[D47CA481-C5E5-3F03-9B04-6634DF5F3121]@0xffffff7f90ce9000\n\nBSD process name corresponding to current thread: kernel_task\nBoot args: agdpmod=pikera\n\nMac OS version:\n19E266\n\nKernel version:\nDarwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15\/RELEASE_X86_64\nKernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6\nKernel slide:     0x000000000f600000\nKernel text base: 0xffffff800f800000\n__HIB  text base: 0xffffff800f700000\nSystem model name: iMac19,1 (Mac-AA95B1DDAB278B95)\nSystem shutdown begun: NO\nPanic diags file available: YES (0x0)\n\nSystem uptime in nanoseconds: 3971867653\nlast loaded kext at 3947663107: >!AHDAHardwareConfigDriver\t283.15 (addr 0xffffff7f91ebe000, size 16384)\nloaded kexts:\ncom.insanelymac.RealtekRTL8111\t2.2.2\nru.joedm.SMCSuperIO\t1.1.1\nas.vit9696.SMCProcessor\t1.1.1\nas.vit9696.VirtualSMC\t1.1.1\nas.vit9696.!AALC\t1.4.7\nas.vit9696.WhateverGreen\t1.3.7\nas.vit9696.Lilu\t1.4.2\n>!AHDAHardwareConfigDriver\t283.15\n>!AHDA\t283.15\n>!AGraphicsDevicePolicy\t5.1.16\n@AGDCPluginDisplayMetrics\t5.1.16\n>!AHV\t1\n|IOUserEthernet\t1.0.1\n|IO!BSerialManager\t7.0.4f6\n>pmtelemetry\t1\n@Dont_Steal_Mac_OS_X\t7.0.0\n>!A!IKBLGraphics\t14.0.5\n>!AGFXHDA\t100.1.426\n>ACPI_SMC_PlatformPlugin\t1.0.0\n>!A!ICFLGraphicsFramebuffer\t14.0.5\n>!A16X50ACPI\t3.2\n>!A!IPCHPMC\t2.0.1\n>!A!ISlowAdaptiveClocking\t4.0.0\n>!AFIVRDriver\t4.1.0\n@private.KextAudit\t1.0\n|SCSITaskUserClient\t422.101.1\n|IO!BUSBDFU\t7.0.4f6\n>!AFileSystemDriver\t3.0.1\n>!AVirtIO\t1.0\n@filesystems.hfs.kext\t522.100.5\n@!AFSCompression.!AFSCompressionTypeDataless\t1.0.0d1\n@BootCache\t40\n@!AFSCompression.!AFSCompressionTypeZlib\t1.0.0\n@filesystems.apfs\t1412.101.1\n>AirPort.BrcmNIC\t1400.1.1\n>!AAHCIPort\t341.0.2\n>!ARTC\t2.0\n>!AACPIButtons\t6.1\n>!AHPET\t1.8\n>!ASMBIOS\t2.1\n>!AAPIC\t1.7\n$!AImage4\t1\n@nke.applicationfirewall\t303\n$TMSafetyNet\t8\n@!ASystemPolicy\t2.0.0\n|EndpointSecurity\t1\n>DspFuncLib\t283.15\n@kext.OSvKernDSPLib\t529\n>!AGraphicsControl\t5.1.16\n>!AHDA!C\t283.15\n|IOHDA!F\t283.15\n|IOAVB!F\t840.3\n>!ASSE\t1.0\n@!AGPUWrangler\t5.1.16\n>IOPlatformPluginLegacy\t1.0.0\n>X86PlatformPlugin\t1.0.0\n|IONDRVSupport\t575.1\n@!AGraphicsDeviceControl\t5.1.16\n|IOAccelerator!F2\t438.4.5\n|IOGraphics!F\t575.1\n>!A16X50Serial\t3.2\n>IOPlatformPlugin!F\t6.0.0d8\n>!ASMBusPCI\t1.0.14d1\n|IOSlowAdaptiveClocking!F\t1.0.0\n@plugin.IOgPTPPlugin\t840.3\n|IOEthernetAVB!C\t1.1.0\n|Broadcom!BHost!CUSBTransport\t7.0.4f6\n|IO!BHost!CUSBTransport\t7.0.4f6\n|IO!BHost!CTransport\t7.0.4f6\n|IO!B!F\t7.0.4f6\n|IO!BPacketLogger\t7.0.4f6\n>usb.IOUSBHostHIDDevice\t1.2\n>usb.cdc\t5.0.0\n>usb.networking\t5.0.0\n>usb.!UHostCompositeDevice\t1.2\n>usb.!UHub\t1.2\n>!UMergeNub\t900.4.2\n|IOAudio!F\t300.2\n@vecLib.kext\t1.2.0\n|IOSerial!F\t11\n|IOSurface\t269.11\n@filesystems.hfs.encodings.kext\t1\n>!AXsanScheme\t3\n>usb.!UHostPacketFilter\t1.0\n|IOUSB!F\t900.4.2\n|IO80211!F\t1200.12.2b1\n>mDNSOffloadUserClient\t1.0.1b8\n>corecapture\t1.0.4\n|IOSkywalk!F\t1\n|IONVMe!F\t2.1.0\n>!AEFINVRAM\t2.1\n|IOAHCI!F\t290.0.1\n>usb.!UXHCIPCI\t1.2\n>usb.!UXHCI\t1.2\n>!AEFIRuntime\t2.1\n|IOHID!F\t2.0.0\n$quarantine\t4\n$sandbox\t300.0\n@kext.!AMatch\t1.0.0d1\n>DiskImages\t493.0.0\n>!AFDEKeyStore\t28.30\n>!AEffaceable!S\t1.0\n>!AKeyStore\t2\n>!UTDM\t489.101.1\n|IOSCSIBlockCommandsDevice\t422.101.1\n>!ACredentialManager\t1.0\n>KernelRelayHost\t1\n>!ASEPManager\t1.0.1\n>IOSlaveProcessor\t1\n|IOUSBMass!SDriver\t157.101.3\n|IOSCSIArchitectureModel!F\t422.101.1\n|IO!S!F\t2.1\n|IOUSBHost!F\t1.2\n>!UHostMergeProperties\t1.2\n>usb.!UCommon\t1.0\n>!ABusPower!C\t1.0\n|CoreAnalytics!F\t1\n>!AMobileFileIntegrity\t1.0.5\n@kext.CoreTrust\t1\n|IOTimeSync!F\t840.3\n|IONetworking!F\t3.4\n|IOReport!F\t47\n>!AACPIPlatform\t6.1\n>!ASMC\t3.1.9\n>watchdog\t1\n|IOPCI!F\t2.9\n|IOACPI!F\t1.4\n@kec.pthread\t1\n@kec.corecrypto\t1.0\n@kec.Libm\t1\n\n\n"

**Comment by Sway-Chan** [comment]
目前还有一个问题，由于我之前是用DP线进入系统的，发现如果插入HDMI的线，进度条完成后进入到桌面会黑屏，换上DP线才会有所显示，估计就是这个HDMI无法正常驱动导致的问题了，把声卡的仿冒ID改成0B000000之后，前置面板正常出声音。

**Comment by Sway-Chan** [comment]
我想请教一下OC的啰嗦模式如何完全开启，我操作黑果小兵的操作，但是启动的时候显示的是黑屏并未打印任何相关日志，boot-args已经添加-v，改成65模式输出到efi目录打开日志文件显示也是为空。

**Comment by igarashikenshin** [comment]
https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html
你可以参考下这篇文章

**Comment by Sway-Chan** [comment]
昨晚我特地拔了一张A卡，插上去之后按照您的ID能正常进入了，查了下那个ID值是把集显当成加速卡，应该是这样导致纯集显模式无法正常进入，插上独显之后睡眠也正常了。
不过不知道您是否有碰到A卡启动第一阶段到第二阶段的时候显示器会出现短暂的无信号，我有搜到一篇类似情况的，但是没有给出解决方法。然后声卡的话，只能用0B000000前置面板才能出声。您的ID我这边不太适用。

**Comment by igarashikenshin** [comment]
核显HDMI 音频唤醒后导致重启的问题，将下面的代码放到 KernelToPatch 。
<dict>
    <key>Comment</key>
    <string>fix reboot after wake from sleep</string>
    <key>Disabled</key>
    <false/>
    <key>Find</key>
    <data>
    Y29tLmFwcGxlAF9fa2VybmVsX18A
    </data>
    <key>MatchOS</key>
    <string>10.15.x</string>
    <key>Replace</key>
    <data>
    bm90LmFwcGxlAF9fa2VybmVsX18A
    </data>
   </dict>
