### ISSUE TITLE
AppleSmcIO主要用来替换VirtualSmc.efi

### ISSUE THREAD

**Issue by Sway-Chan** [igarashikenshin/Hackintosh-Asus-Prime-Z390P_i9-9900K_RX580#4]
如果开启了AppleSmcIO，则无需放置VirtualSmc.efi。两个二选其一即可。

**Comment by igarashikenshin** [comment]
这个文档在0.5.6的时候看过，现在0.5.8无论是否勾选该选项都无任何变化

发自我的iPhone

在 2020年5月24日，12:25，Sway Chan <notifications@github.com> 写道：

﻿

如果开启了AppleSmcIO，则无需放置VirtualSmc.efi。两个二选其一即可。

**Comment by Sway-Chan** [comment]
现在的版本，这个功能貌似是默认开启了。我忘了在哪边的文档看到的。之前测试，我没放VirtualSmc.efi也没开AppleSmcIO，不影响实际使用。不过目前还是勾选了AppleSmcIO

**Comment by igarashikenshin** [comment]
VirtualSmc.efi被从0.5.4开始被FwRuntime（后更名为openruntime）内置了，问题在于调用它的方式，在0.5.4的官方文档中，在protocol中打开AppleSmcIo即可调用，但在0.5.6之后，即是不调用，smc相关依赖也能够正常运作，是否可以看作openruntime中加入了判断（启用AppleSmcIo调用VirtualSmc，若不启用则默认使用内置协议“或许还是VirtualSmc”？）

**Comment by Sway-Chan** [comment]
目前针对这个选项暂时也没有发现太多详细的说明，都只是简单的提到而已。
